"""
Django settings for sigma project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4%kcgrhibzx*7#-3ts9p(w6ed$-6r17m(x88j+f*)e9jwcv)+c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',
    'rest_framework',
    'dry_rest_permissions',
    'corsheaders',
    'debug_toolbar',
    'rest_framework_swagger',
    'oauth2_provider',
    'django_nose',
    'tornado_websockets',

    'sigma_core.apps.SigmaCoreConfig',
    'sigma_files.apps.SigmaFilesConfig',
    'sigma_chat.apps.SigmaChatConfig',
)

MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # TODO : adapt for production

ROOT_URLCONF = 'sigma.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigma.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Rest framework
REST_FRAMEWORK = {
    'DEFAULT_MODEL_SERIALIZER_CLASS':
        'rest_framework.serializers.HyperlinkedModelSerializer',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',  # TODO: remove
        # 'rest_framework.authentication.BasicAuthentication',  # TODO: remove
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter'
    ),
    'TEST_REQUEST_DEFAULT_FORMAT': 'json'
}

# OAuth2
OAUTH2_PROVIDER = {
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}

# Swagger REST
SWAGGER_SETTINGS = {
    'enabled_methods': [
        'get',
        'post',
        'put',
        'delete'
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
ENV_PATH = os.path.abspath(os.path.dirname(__file__))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(ENV_PATH, 'static')

MEDIA_ROOT = os.path.join(ENV_PATH, '../media/')
MEDIA_URL = '/media/'

# CORS headers
CORS_ORIGIN_ALLOW_ALL = True

# Test (django_nose conf)
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
NOSE_ARGS = ['--nocapture', '--nologcapture', '--with-coverage', '--cover-package=sigma,sigma_core,sigma_files', ] # To display debug during testing

AUTH_USER_MODEL = 'sigma_core.User'

import tornado_websockets
from tornado import websocket
from tornado.web import StaticFileHandler
from tornado_chat import MainHandler, ClientWSConnection, ChatHandler

ch = ChatHandler()

TORNADO = {
    'port': 8000,    # 8000 by default
    'handlers': [
        (r'/tornado/chat/', MainHandler, {'chat_handler': ch}),
        (r"/tornado/ws/(.*)", ClientWSConnection, {'chat_handler': ch}),
        (r'%s(.*)' % STATIC_URL, StaticFileHandler, {'path': STATIC_ROOT}),
        tornado_websockets.django_app
    ],  # [] by default
    'settings': {
        'debug': True,
    },  # {} by default
}
