# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0008_auto_20160108_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='GroupMember',
        ),
        migrations.AlterField(
            model_name='user',
            name='invited_to_groups',
            field=models.ManyToManyField(blank=True, related_name='invited_users', to='sigma_core.Group'),
        ),
    ]
