# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0009_auto_20160111_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sigma_core.Group')),
                ('design', models.CharField(max_length=255)),
            ],
            bases=('sigma_core.group',),
        ),
    ]
