# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0009_auto_20160111_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('validator_values', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('html_name', models.CharField(choices=[('text', 'Text'), ('none', 'None')], default='none', max_length=255)),
                ('values', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='groupcustomfield',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sigma_core.Validator'),
        ),
        migrations.AddField(
            model_name='group',
            name='custom_fields',
            field=models.ManyToManyField(related_name='_group_custom_fields_+', to='sigma_core.GroupCustomField'),
        ),
    ]
