# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0011_schoolgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAcknowledgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='school',
        ),
        migrations.AddField(
            model_name='group',
            name='resp_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sigma_core.School'),
        ),
        migrations.DeleteModel(
            name='SchoolGroup',
        ),
        migrations.AddField(
            model_name='groupacknowledgment',
            name='asking_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_recognizers', to='sigma_core.Group'),
        ),
        migrations.AddField(
            model_name='groupacknowledgment',
            name='validator_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_acknowledgments', to='sigma_core.Group'),
        ),
    ]
