# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0011_auto_20160126_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('validator_values', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupcustomfield',
            name='validator',
        ),
        migrations.AlterUniqueTogether(
            name='groupmembercustomfield',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupmembercustomfield',
            name='field',
        ),
        migrations.RemoveField(
            model_name='groupmembercustomfield',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='group',
            name='custom_fields',
        ),
        migrations.DeleteModel(
            name='GroupCustomField',
        ),
        migrations.DeleteModel(
            name='GroupMemberCustomField',
        ),
        migrations.AddField(
            model_name='groupfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sigma_core.Group'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sigma_core.Validator'),
        ),
    ]
