# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0012_auto_20160127_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupacknowledgment',
            name='parent_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='sigma_core.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupacknowledgment',
            name='subgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_parents', to='sigma_core.Group'),
            preserve_default=False,
        ),
    ]
