# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 08:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0012_auto_20160126_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfield',
            name='validator_values',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='validator',
            name='values',
            field=jsonfield.fields.JSONField(),
        ),
    ]
