# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0013_auto_20160129_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='id',
        ),
        migrations.AlterField(
            model_name='validator',
            name='html_name',
            field=models.CharField(choices=[('text', 'Text'), ('none', 'None')], default='none', max_length=255, primary_key=True, serialize=False),
        ),
    ]
