# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 10:09
from __future__ import unicode_literals

from django.db import migrations

def move_foreignkeys(apps, schema_editor):
    GroupAcknowledgment = apps.get_model("sigma_core", "GroupAcknowledgment")
    for ga in GroupAcknowledgment.objects.all():
        ga.subgroup = ga.asking_group
        ga.parent_group = ga.validator_group
        ga.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0013_auto_20160201_1108'),
    ]

    operations = [
        migrations.RunPython(move_foreignkeys),
    ]
