# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0014_auto_20160129_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sigma_core.GroupField')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sigma_core.GroupMember')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmembervalue',
            unique_together=set([('membership', 'field')]),
        ),
    ]
