# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0015_auto_20160201_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('validator_values', jsonfield.fields.JSONField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sigma_core.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMemberValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sigma_core.GroupField')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sigma_core.GroupMember')),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('display_name', models.CharField(max_length=255)),
                ('html_name', models.CharField(choices=[('text', 'Text'), ('none', 'None')], default='none', max_length=255, primary_key=True, serialize=False)),
                ('values', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='groupfield',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sigma_core.Validator'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembervalue',
            unique_together=set([('membership', 'field')]),
        ),
    ]
