# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0017_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='visibility',
        ),
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
