# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0018_auto_20160205_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
