# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0019_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sigma_core.Group')),
                ('design', models.CharField(max_length=255)),
            ],
            bases=('sigma_core.group',),
        ),
        migrations.RemoveField(
            model_name='school',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='group',
            name='resp_school',
        ),
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.AddField(
            model_name='group',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='group',
            name='resp_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sigma_core.Cluster'),
        ),
        migrations.AddField(
            model_name='user',
            name='clusters',
            field=models.ManyToManyField(related_name='users', to='sigma_core.Cluster'),
        ),
    ]
