# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0020_auto_20160208_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sigma_files.Image'),
        ),
    ]
