# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0021_auto_20160208_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='resp_cluster',
        ),
        migrations.AddField(
            model_name='group',
            name='resp_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sigma_core.Group'),
        ),
    ]
