# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0022_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', through='sigma_core.GroupMember', to='sigma_core.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clusters',
            field=models.ManyToManyField(related_name='cluster_users', to='sigma_core.Cluster'),
        ),
    ]
