# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0023_auto_20160215_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='req_rank_create_group_publication',
            field=models.SmallIntegerField(default=10),
        ),
    ]
