# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0024_auto_20160506_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupacknowledgment',
            name='delegate_admin',
            field=models.BooleanField(default=True),
        ),
    ]
