# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0025_groupacknowledgment_delegate_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='resp_group',
        ),
    ]
