# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0026_remove_group_resp_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='default_member_rank',
        ),
        migrations.RemoveField(
            model_name='group',
            name='req_rank_accept_join_requests',
        ),
        migrations.RemoveField(
            model_name='group',
            name='req_rank_demote',
        ),
        migrations.RemoveField(
            model_name='group',
            name='req_rank_invite',
        ),
        migrations.RemoveField(
            model_name='group',
            name='req_rank_kick',
        ),
        migrations.RemoveField(
            model_name='group',
            name='req_rank_modify_group_infos',
        ),
        migrations.RemoveField(
            model_name='group',
            name='req_rank_promote',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='perm_rank',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_be_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_kick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_modify_group_infos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='is_super_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
