# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0027_auto_20160917_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='need_validation_to_join',
            field=models.BooleanField(default=False),
        ),
    ]
