# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0028_group_need_validation_to_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmembervalue',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupmembervalue',
            name='field',
        ),
        migrations.RemoveField(
            model_name='groupmembervalue',
            name='membership',
        ),
        migrations.DeleteModel(
            name='Validator',
        ),
        migrations.RemoveField(
            model_name='groupfield',
            name='validator',
        ),
        migrations.RemoveField(
            model_name='groupfield',
            name='validator_values',
        ),
        migrations.AddField(
            model_name='group',
            name='confidentiality',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='accept',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='multiple_values_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Number'), (1, 'String'), (2, 'Choice'), (3, 'Email')], default=0),
        ),
        migrations.AlterField(
            model_name='groupfield',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.DeleteModel(
            name='GroupMemberValue',
        ),
        migrations.AddField(
            model_name='groupfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sigma_core.GroupField'),
        ),
        migrations.AddField(
            model_name='groupfieldvalue',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sigma_core.GroupMember'),
        ),
        migrations.AlterUniqueTogether(
            name='groupfieldvalue',
            unique_together=set([('membership', 'field')]),
        ),
    ]
