# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0031_auto_20161005_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='confidentiality',
            new_name='user_confidentiality',
        ),
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
