# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0032_auto_20161123_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_private',
        ),
    ]
