checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    tests:
        override:
            -
                command: 'python manage.py test'
                coverage:
                    file: '.coverage'
                    config: '.coveragerc'
                    format: 'py-cc'
