checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    dependencies:
        before:
            - "pip install -r requirements/dev.txt"
            - "pip install -r requirements/prod.txt"
    tests:
        override:
            -
                command: 'python manage.py test'
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
