# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import sigma_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='file',
            field=models.ImageField(max_length=255, upload_to=sigma_files.models.profile_img_path),
        ),
    ]
