# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_core', '0023_auto_20160215_1346'),
        ('sigma_publications', '0002_publicationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='posted_in',
            field=models.ManyToManyField(related_name='publications', through='sigma_publications.GroupPost', to='sigma_core.Group'),
        ),
    ]
