# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_publications', '0003_publication_posted_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
    ]
