# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_publications', '0004_auto_20160215_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='poster_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publications', to='sigma_core.Group'),
        ),
    ]
