# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_publications', '0005_auto_20160215_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 15, 16, 46, 19, 370696, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
